kiwibis/Capstone

- client/package-lock.json
- package.json
- server/util/index.js
- server/util/parser.js
- server/util/prettier.js
> feat(editing): Utility function for condensing api-returned JSON #5

- client/package-lock.json
- client/src/components/home-page/home-page.js
- client/src/components/home-page/index.js
- client/src/components/index.js
- client/src/components/navbar.js
- client/src/components/photo-capture.js
- client/src/index.css
- client/src/routes.js
> feat(react): Component that tells users to upload/take a pic

- client/src/App.js
- client/src/components/navbar.js
- package-lock.json
- package.json
> feat: included a hamburger menu icon in navbar, whose view toggles when clicked

- client/components/edit-page/edit-page.js
- client/routes.js
- client/store/code.js
- public/style.css
> feat(react): Component with text box and input field

- client/components/edit-page/edit-page.js
- evalTest.js
- package-lock.json
- package.json
- public/index.html
- public/style.css
- server/api/images.js
- server/util/balanceBrackets.js
- server/util/tests/balanceBrackets.spec.js
- webpack.config.js
> refactor: code text using react-codemirror

- client/components/edit-page/edit-page.js
- server/api/images.js
- server/util/simplifyVisionResponse.js
> refactor: auto-resize CodeMirror, removed prettier from utils

- public/style.css
> fix: CodeMirror auto-resize in style.css

- client/components/edit-page/index.js
- client/components/edit-page/results.js
> refactor: eval code handling & rendering empty inputs in results

- client/components/edit-page/index.js
- client/components/photo-capture.js
- package-lock.json
- package.json
- public/style.css
- server/api/images.js
> fix: Image orientation

- server/api/images.js
- server/util/errorCorrecting.js
- server/util/index.js
> feat: Error correcting - words split on camel case

- server/api/images.js
> refactor: potential heroku fix

- server/api/images.js
> heroku testing

- .eslintrc.json
- client/components/edit-page/evaluator.js
- client/components/edit-page/index.js
- client/components/edit-page/results.js
> feat: display error message given by eval

- server/util/errorCorrecting.js
> refactor: combine conditional in error correcting line 101

- public/style.css
- server/util/errorCorrecting.js
> Refactored master error corrector

- client/components/edit-page/edit-page.js
- client/components/edit-page/results.js
- client/util/evaluator.js
> feat: evaluating user code using webworkers

- server/util/errorCorrecting.js
> feat: error correcting triple equals

- client/components/edit-page/edit-page.js
- client/util/evaluator.js
> fix: unicode quotes will be replaced with ascii quotes

- client/components/edit-page/input-output-wrapper.js
> fix: scrollable test cases & results view

- client/components/auth-form.js
- client/components/navbar.js
> fix: logout

- client/store/user.js
- script/seed.js
- server/api/trainingData.js
- server/auth/index.js
- server/db/models/user.js
> chore: edit routes to send user & their functions from database

- client/routes.js
- public/style.css
> fix: merge conflict error

- client/components/user-home.js
> fix: passing only necessary props to Carousel

- server/util/errorCorrecting.js
> fix: 2 double quotes bug
